Returning true/success once directory is created
dell/csi-powermax pull request #240
Opened 2023-10-27 07:25 UTC by delldubey

# Description
Returning true/success once the directory is created for mounting.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/1012|

# Checklist:

- [x] Have you run format,vet & lint checks against your submission?
- [x] Have you made sure that the code compiles?
- [x] Did you run the unit & integration tests successfully?
- [ ] Have you maintained at least 90% code coverage?
- [x] Have you commented your code, particularly in hard-to-understand areas
- [ ] Have you done corresponding changes to the documentation
- [x] Did you run tests in a real Kubernetes cluster?
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration
- Cluster Tests
- Unit Tests
569 scenarios (569 passed)
3990 steps (3990 passed)
PASS

2023-10-27 08:19 UTC, tssushma approved these changes
LGTM

2023-10-27 11:33 UTC, boyamurthy approved these changes

2023-10-27 11:39 UTC, gallacher requested changes
Is this a fix for a bug? You're linking to a release activities feature which is far too generic.

2023-10-27 12:31 UTC, delldubey commented
> Is this a fix for a bug? You're linking to a release activities feature which is far too generic.

Updated the csm-issue link.

2023-10-30 11:19 UTC, gallacher approved these changes

2023-10-30 11:29 UTC, merged