KRV-26723: add retry step 2 i.e. LinkVolumeToVolume in the subsequent CreateVolume calls
dell/csi-powermax pull request #319
Opened 2024-08-14 14:25 UTC by MaksimDell

# Description
When [creating PVCs with PVCs as source](https://dell.github.io/csm-docs/docs/csidriver/features/powermax/#creating-pvcs-with-pvcs-as-source) the code does below operations on a high level

CreateVolumeInStorageGroupS - [controller.go#L751](https://github.com/dell/csi-powermax/blob/2062fbd047b4fd36842f8dd7552c02205da5fbef/service/controller.go#L751)
LinkVolumeToVolume - [controller.go#L799](https://github.com/dell/csi-powermax/blob/2062fbd047b4fd36842f8dd7552c02205da5fbef/service/controller.go#L799)
CreateSnapshotFromVolume
LinkVolumeToSnapshot
If there are any failure during 2.1 or 2.2 the driver does not clean up the volume created in step 1. As a result the subsequent CreateVolume call return success due to idempotency. However, this is incorrect because it results in an empty new volume instead of a clone of the source volume.

To fix this issue driver should retry step 2 i.e. LinkVolumeToVolume  in the subsequent CreateVolume calls

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
[|KRV-26628](https://jira.cec.lab.emc.com/browse/KRV-26628) |

# Checklist:

- [ ] Have you run format,vet & lint checks against your submission?
- [ ] Have you made sure that the code compiles?
- [ ] Did you run the unit & integration tests successfully?
- [ ] Have you maintained at least 90% code coverage?
- [ ] Have you commented your code, particularly in hard-to-understand areas
- [ ] Have you done corresponding changes to the documentation
- [ ] Did you run tests in a real Kubernetes cluster?
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
We cannot simulate the customers environment, so we should create nightly build and provide it to customer in order to check the fix

2024-08-14 16:02 UTC, bjiang27 approved these changes

2024-08-14 16:39 UTC, gallacher requested changes
Please add new unit tests and integration tests to account for the code changes being made here.  The PR should also indicate what tests have been executed and provide the results as well to ensure quality is where it needs to be.

2024-08-14 16:58 UTC, AronAtDell commented
Checks are failing, please ensure that you address the failed checks before approving. Thanks!

2024-08-16 10:09 UTC, MaksimDell commented
> Also, checks are failing, please ensure that you address the failed checks before approving. Thanks!

There are a lot of linting errors in files that are not connected to this fix. Do you want me to fix them and include them in this PR or create a separate PR for this?

2024-08-16 12:51 UTC, MaksimDell commented
Looks like the linter got updated yesterday to 1.60.1 and some new issues are found. An initial look indicates issues with passing non const format parameters to printf related functions. That exceeds the scope of what I had planned to accomplish.

2024-08-19 11:39 UTC, MaksimDell commented
Closing the PR. Need to update the test and change the branch name

2024-08-19 11:39 UTC, closed without merging