Fix for sidecar installation failure if k8s worker nodes are not in ~/.ssh/known_hosts
dell/csi-powermax pull request #47
Opened 2022-01-06 17:18 UTC by sharmilarama

# Description
This PR addresses an issue with sidecar installation failure when the remote k8s worker nodes have not yet been added to the ~/.ssh/known_hosts file. While running SSH commands to check connectivity to the authorization proxy there is an additional message in the response "Warning: Permanently added '1.2.3.4' (ECDSA) to the list of known hosts.". This PR adds changes to ignore this warning message to get the response code in the next line.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/147 |

# Checklist:

- [ ] Have you run format,vet & lint checks against your submission?
- [ ] Have you made sure that the code compiles?
- [ ] Did you run the unit & integration tests successfully?
- [ ] Have you maintained at least 90% code coverage?
- [ ] Have you commented your code, particularly in hard-to-understand areas
- [ ] Have you done corresponding changes to the documentation
- [ ] Did you run tests in a real Kubernetes cluster?
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

2022-01-11 07:07 UTC, delldubey approved these changes
lgtm

2022-01-11 07:10 UTC, delldubey requested changes
Please run the checklist as shown in the PR.

2022-01-12 03:18 UTC, boyamurthy approved these changes
looks good to me .

2022-01-13 07:45 UTC, delldubey approved these changes
looks good

2022-01-13 11:08 UTC, merged